name: revive
description: "Revive AI - Offline, Real-time CPR Guidance"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sensors_plus: ^7.0.0
  flutter_tts: ^4.2.5
  audioplayers: ^6.6.0
  http: ^1.2.0
  google_fonts: ^6.0.0
  wakelock_plus: ^1.2.8
  speech_to_text: ^7.3.0
  permission_handler: ^12.0.1
  url_launcher: ^6.3.0
  flutter_phone_direct_caller: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 28

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/Chest_compressions.gif
    - assets/CPR_HAND PLACEMENT.png
    - assets/CPR_RESCUE_BREATH.PNG
    - assets/CHIN_POSITION.jpeg
